"""empty message

Revision ID: 9540d43c926f
Revises: 483405bd072b
Create Date: 2025-01-09 10:36:48.890311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9540d43c926f'
down_revision: Union[str, None] = '483405bd072b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('corelation', sa.Float(), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('y_intercept', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_standards_id'), 'standards', ['id'], unique=True)
    op.create_index(op.f('ix_standards_user_id'), 'standards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standards_user_id'), table_name='standards')
    op.drop_index(op.f('ix_standards_id'), table_name='standards')
    op.drop_table('standards')
    # ### end Alembic commands ###
