"""empty message

Revision ID: a9373a7acf18
Revises: 718123df72b4
Create Date: 2025-09-19 10:13:01.153612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9373a7acf18'
down_revision: Union[str, None] = '718123df72b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('experiments_project_id_fkey', 'experiments', type_='foreignkey')
    op.create_foreign_key(None, 'experiments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('standards_user_id_fkey', 'standards', type_='foreignkey')
    op.create_foreign_key(None, 'standards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'standards', type_='foreignkey')
    op.create_foreign_key('standards_user_id_fkey', 'standards', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'experiments', type_='foreignkey')
    op.create_foreign_key('experiments_project_id_fkey', 'experiments', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
