"""empty message

Revision ID: f49771b45a6a
Revises: 9a1e90f9b29d
Create Date: 2025-01-09 18:16:45.455403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49771b45a6a'
down_revision: Union[str, None] = '9a1e90f9b29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('standards_name_key', 'standards', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('standards_name_key', 'standards', ['name'])
    # ### end Alembic commands ###
