version: "3.8"


services:
  postgres:
    container_name: lowry-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  minio:
    image: quay.io/minio/minio:latest
    container_name: lowry-minio
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data    
      - minio-config:/root/.minio
    command: server /data --console-address ":9001"

  redis:
    container_name: lowry-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend:
    container_name: lowry-backend
    build: ./backend
    image: "lowry-api:v1"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
      REFRESH_TOKEN_SECRET_KEY: ${REFRESH_TOKEN_SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  celery:
    container_name: lowry-celery
    build: ./backend
    image: "lowry-celery:v1"
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
      REFRESH_TOKEN_SECRET_KEY: ${REFRESH_TOKEN_SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    command: celery -A src.celery_worker worker --loglevel=info
    depends_on:
      - redis

  frontend:
    container_name: lowry-frontend
    image: "lowry-frontend:v1"
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev


volumes:
  pg-data:
    driver: local
  minio-data:
  minio-config: