version: "3.8"


services:
  postgres:
    container_name: lowry-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  minio:
    image: quay.io/minio/minio:latest
    container_name: lowry-minio
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data    
      - minio-config:/root/.minio
    command: server /data --console-address ":9001"

  redis:
    container_name: lowry-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"


volumes:
  pg-data:
    driver: local
  minio-data:
  minio-config: