version: "3.8"


services:
  postgres:
    container_name: lowry-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    container_name: lowry-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"


volumes:
  pg-data:
    driver: local