apiVersion: v1
kind: Secret
metadata:
  name: lowry-secrets
  namespace: lowry

data:
  postgres_db: bG93cnk=
  user: Z2lvcmdp
  password: Z2lvcmdpNTU1NQ==

  access_token_secret_key: ODBiM2U0YjViZjY0NDhlMGE0MDE2MGU3ZWNjZDFiM2E4NDdjN2EyOWIwZGY0NzI1YWJjY2ZjNDExZGY5Mzg1Mg==
  refresh_token_secret_key: NDViZWI5NDdhZDVmNGZhYzkyMmNmZWJjNDlmNDU5M2RjMmE3NDBjN2Y2NDY0M2FmYjg3ZjViYjRmMGU0NjA4Yg==
  algorithm: SFMyNTY=

  minio_bucket: bG93cnktYnVja2V0

  MAIL_USERNAME: 
  MAIL_PASSWORD: